version: '3'

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5445:5432"